[package]
name = 'gpu'
version = '0.0.0'
edition = '2018'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com']

[dependencies]
combustion = {path=".."}
ash = ''
fehler = ''
anyhow = ''

[build-dependencies]
combustion = {path='..'}
shaderc = ''
iter = {git='https://github.com/Matthias-Fauconneau/iter'}
itertools = ''

[[bin]]
name = 'gpu'
path = 'main.rs'
