cargo-features=['edition2021']
package= { name= 'combustion', description= 'Chemical reaction kinetics and species transport properties', version= '0.0.0', edition= '2021', default-run = 'plot' }
features= { gpu=['spirv','vulkan','anyhow','fehler'], plot=['cvode','ui','image','png','anyhow'], default=['itertools'] }
bin=[
	{name='test', path='test.rs', required-features=['itertools']},
	{name='cantera', path='cantera.rs', required-features=['itertools','rand']},
	{name='plot', path='plot.rs', required-features=['plot']}
]

[dependencies]
anyhow= {optional=true, version='*' }
fehler= {optional=true, version='*' }
itertools= {optional=true, version='*' }
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
ast= {path='ast'}
yaml-model= {path='yaml'}
chemistry= {path='chemistry'}
reaction= {path='reaction'}
ir= {optional=true, path='ir', features=['jit']}
vulkan= {optional=true, path='vulkan'}
spirv= {optional=true, path='spirv', package='ast-spirv'}
rand= {optional=true, version='*'}
cvode= {optional=true, path='cvode'}
ui= {optional=true, git='https://github.com/Matthias-Fauconneau/ui', features= ['plot']}
image= {optional=true, git='https://github.com/Matthias-Fauconneau/image'}
png= {optional=true, package= 'image', version='', default-features=false, features= ['png']}
transport= {optional=true, path='transport'}
