[package]
name= 'combustion'
description= 'Chemical reaction kinetics'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[features]
transport= ['nalgebra']
reaction= ['cranelift', 'cranelift-jit', 'cranelift-module', 'cranelift-codegen', 'cranelift-native']
default= ['transport']

[dependencies]
derive_more= ''
strum= ''
strum_macros= ''
fehler= ''
error= {package='anyhow', version=''}
ron= ''
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
serde= ''
linear-map= {features= ['serde_impl'], version=''}
target-lexicon= ''
nalgebra= {optional= true, version=''}
itertools= ''
cranelift= {optional= true, version=''}
cranelift-jit= {optional= true, version=''}
cranelift-module= {optional= true, version=''}
cranelift-codegen= {optional= true, version=''} # features= ['enable-peepmatic']
cranelift-native= {optional= true, version=''}
capstone= {optional= true, version=''}
cranelift-reader= {optional= true, version=''}

[patch.'https://github.com/Matthias-Fauconneau/iter']
iter= {path='../iter'}
