cargo-features= ['edition2021']
package= { name= 'combustion', description= 'Chemical reaction kinetics and species transport properties', version= '0.0.0', edition= '2021', default-run = 'combustion'}
features= { gpu= ['spirv','ash'] }
bin = [ { name= 'combustion', path= 'cpu.rs' }, { name= 'combustion-gpu', path= 'gpu.rs' } ]

[dependencies]
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
ast= {path='ast'}
yaml-model= {path='yaml'}
chemistry= {path='chemistry'}
reaction= {path='reaction'}
transport= { optional=true, path='transport'}
itertools='*'
spirv= { optional=true, path= 'spirv', package= 'ast-spirv', version='*' }
ash= { optional=true, version='*' }

[patch.'https://github.com/Matthias-Fauconneau/num']
num={path='../Code/num'}
