[package]
name = "combustion"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
iter = {path='../iter'}
num = {path='../num'}
serde = ''
ron = ''
fehler = ''
anyhow = ''
itertools = ''
