[package]
name= 'combustion'
description= 'Chemical reaction kinetics'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[features]
reaction= ['cranelift']
jit= ['cranelift-native', 'cranelift-codegen', 'cranelift-module', 'cranelift-jit']
transport= ['nalgebra']
#default=['transport']
default=['reaction','jit']

[dependencies]
derive_more='*'
strum='*'
strum_macros='*'
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
serde='*'
ron='*'
linear-map= {features= ['serde_impl'], version='*'}
nalgebra= {optional=true, version='*'}
cranelift= {optional=true, version='*'}
cranelift-codegen= {optional=true, version='*'}
cranelift-module= {optional=true, version='*'}
cranelift-native= {optional=true, version='*'}
cranelift-jit= {optional=true, version='*'}
