[package]
name= 'combustion'
description= 'Chemical reaction kinetics'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
derive_more= ''
strum= ''
strum_macros= ''
fehler= ''
error= {package='anyhow', version=''}
ron= ''
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
serde= ''
linear-map= {version='', features = ['serde_impl']}
target-lexicon= ''
nalgebra= {optional= true, version=''}
itertools= ''
cranelift= ''
cranelift-jit= ''
cranelift-module= ''
cranelift-object= ''
cranelift-reader= ''
cranelift-interpreter= ''
capstone= '' #|iced-x86? (pure Rust)
pretty_env_logger= ''

[patch.crates-io]
cranelift= {path= '../wasmtime/cranelift/umbrella'}
cranelift-jit= {path= '../wasmtime/cranelift/jit'}
cranelift-module= {path= '../wasmtime/cranelift/module'}
cranelift-object= {path= '../wasmtime/cranelift/object'}
cranelift-reader= {path= '../wasmtime/cranelift/reader'}
cranelift-interpreter= {path= '../wasmtime/cranelift/interpreter'}
