[package]
name= 'combustion'
description= 'Chemical reaction kinetics'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
fehler= ''
ron= ''
model={path='model'}
system={path='system'}
macro={path='macro'}
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
serde= ''
linear-map= {version='', features = ['serde_impl']}
unwrap= ''
nalgebra= {optional= true, version=''}

[patch.'https://github.com/Matthias-Fauconneau/num']
num= {path= '../num'}
