[package]
name= 'combustion'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
iter = {path='../iter'} #{git='https://github.com/Matthias-Fauconneau/iter'}
num = {path='../num'} #{git='https://github.com/Matthias-Fauconneau/num'}
serde = ''
linear-map = {version='', features = ['serde_impl']}
ron = ''
fehler = ''
itertools = ''
rayon= ''
nalgebra = ''