[package]
name= 'combustion'
description= 'Chemical reaction kinetics'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
derive_more= ''
strum= ''
strum_macros= ''
fehler= ''
error= {package='anyhow', version=''}
ron= ''
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
serde= ''
linear-map= {version='', features = ['serde_impl']}
cranelift= ''
cranelift-jit= ''
cranelift-module= ''
nalgebra= {optional= true, version=''}

#[patch.'https://github.com/Matthias-Fauconneau/num']
#num= {path= '../num'}
