[package]
name= 'reaction'
version= '0.0.0'
edition= '2018'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']

[dependencies]
fehler= ''
anyhow= ''
combustion= {path='..', features=['cranelift']}
iter= {git='https://github.com/Matthias-Fauconneau/iter'}

[lib]
path = 'lib.rs'
