[package]
name = "combustion plot"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
fehler = ''
anyhow = ''
combustion = {path='../ui'}
ui = {path='../ui'}
