[package]
name= 'combustion-cantera'
description= 'Validates transport properties against Cantera'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

#[build-dependencies]
#bindgen= ''

[dependencies]
fehler= ''
error= {package='anyhow', version=''}
iter= {git='https://github.com/Matthias-Fauconneau/iter'}
num= {git='https://github.com/Matthias-Fauconneau/num'}
combustion= {path='..'}
cvode= {path='../cvode', optional=true}
