[package]
name = "combustion-cantera"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
fehler = ''
anyhow = ''
iter = {path='../../iter'}
combustion = {path='..'}
itertools = ''

[[bin]]
name= 'cantera'
path= 'main.rs'
