package={name='ast', description='AST', version='0.0.0', edition='2021'}
lib={path='lib.rs'}
features={interpret=[]}

[dependencies]
iter={git='https://github.com/Matthias-Fauconneau/iter'}
ordered-float='*'
itertools='*'
