[package]
name = 'f'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[lib]
crate-type = ["dylib"]
path = 'main.rs'

[dependencies]
spirv-std = {git='https://github.com/embarkstudios/rust-gpu', branch= 'main'}
